apiVersion: v1
kind: Service
metadata:
  labels:
    app: exdepmain
  name: exdepmain
spec:
  clusterIP: 10.96.158.152
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31636
    port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app: exdepmain
  type: NodePort
